# Generated by Django 4.0.4 on 2022-05-17 19:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfacehex',
            name='airports',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='electric_s',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='eocs',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='fcc_asr',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='h3_index',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='helipads',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='hospitals',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='index_field',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='lulc',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='police_sta',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='population',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='prisons',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='railroads',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='roads',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='schools',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='shape_area',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='shape_leng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='stadium',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='transmissi',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='uasfm_ceil',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='uasfm_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='uasfm_min',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='surfacehex',
            name='wind_farms',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
