# Generated by Django 4.0.4 on 2022-05-19 18:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convAPI', '0003_uavrouteinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uavrouteinput',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326),
        ),
    ]
