# Generated by Django 4.0.4 on 2022-05-23 17:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convAPI', '0004_routemodellinestring'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteModelOutputPoints',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('geoidheight', models.FloatField(null=True)),
                ('terrainnavd88', models.FloatField(null=True)),
                ('terrainwgs84', models.FloatField(null=True)),
                ('units', models.CharField(max_length=5, null=True)),
                ('altitude', models.FloatField(null=True)),
                ('agl', models.FloatField(null=True)),
                ('height_above_takeoff', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
        ),
    ]
